import type { Product, Category } from "./types"

export const categories: Category[] = [
  {
    id: "1",
    name: "Category A",
    slug: "category-a",
    description: "Products in category A",
  },
  {
    id: "2",
    name: "Category B",
    slug: "category-b",
    description: "Products in category B",
  },
  {
    id: "3",
    name: "Category C",
    slug: "category-c",
    description: "Products in category C",
  },
  {
    id: "4",
    name: "Category D",
    slug: "category-d",
    description: "Products in category D",
  },
]

export const products: Product[] = [
  {
    id: "1",
    name: "Product One",
    description: "High-quality product with excellent features and reliable performance. Perfect for everyday use.",
    price: 199.99,
    originalPrice: 249.99,
    image: "/placeholder.svg?height=400&width=400&text=Product+One",
    images: [
      "/placeholder.svg?height=400&width=400&text=Product+One+View+1",
      "/placeholder.svg?height=400&width=400&text=Product+One+View+2",
      "/placeholder.svg?height=400&width=400&text=Product+One+View+3",
      "/placeholder.svg?height=400&width=400&text=Product+One+View+4",
    ],
    category: "Category A",
    inStock: true,
    stockCount: 25,
    rating: 4.5,
    reviewCount: 128,
    tags: ["premium", "quality", "reliable"],
  },
  {
    id: "2",
    name: "Product Two",
    description: "Advanced product with innovative features and modern design for enhanced user experience.",
    price: 299.99,
    image: "/placeholder.svg?height=400&width=400&text=Product+Two",
    category: "Category A",
    inStock: true,
    stockCount: 15,
    rating: 4.7,
    reviewCount: 89,
    tags: ["advanced", "modern", "innovative"],
  },
  {
    id: "3",
    name: "Product Three",
    description: "Comfortable and durable product available in multiple options to suit your preferences.",
    price: 29.99,
    image: "/placeholder.svg?height=400&width=400&text=Product+Three",
    category: "Category B",
    inStock: true,
    stockCount: 50,
    rating: 4.3,
    reviewCount: 45,
    tags: ["comfortable", "durable", "versatile"],
  },
  {
    id: "4",
    name: "Product Four",
    description: "Professional-grade product with ergonomic design and adjustable features for optimal use.",
    price: 449.99,
    originalPrice: 599.99,
    image: "/placeholder.svg?height=400&width=400&text=Product+Four",
    category: "Category C",
    inStock: true,
    stockCount: 8,
    rating: 4.6,
    reviewCount: 67,
    tags: ["professional", "ergonomic", "adjustable"],
  },
  {
    id: "5",
    name: "Product Five",
    description: "Premium product with superior materials and excellent build quality for long-lasting use.",
    price: 79.99,
    image: "/placeholder.svg?height=400&width=400&text=Product+Five",
    category: "Category D",
    inStock: true,
    stockCount: 30,
    rating: 4.4,
    reviewCount: 92,
    tags: ["premium", "superior", "long-lasting"],
  },
  {
    id: "6",
    name: "Product Six",
    description: "Eco-friendly product that combines functionality with environmental responsibility.",
    price: 34.99,
    image: "/placeholder.svg?height=400&width=400&text=Product+Six",
    category: "Category D",
    inStock: false,
    stockCount: 0,
    rating: 4.2,
    reviewCount: 156,
    tags: ["eco-friendly", "functional", "sustainable"],
  },
]
